# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FireURL
email: 9029537@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Easily share links between two devices.
baseurl: "/FireURL-Tutorial" # the subpath of your site, e.g. /blog
url: "https://fireurl.github.io" # the base hostname & protocol for your site
twitter_username: prankymat
github_username:  prankymat

# Build settings
markdown: kramdown
github: [Repository metadata]
